### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by christinazavou** [nicefish666/proj_style#2]
Hi, thanks for sharing your code!
I'm trying to run this method on other data, and I realized your input data consists of a folder named 3dlines which contains .bmp files.
Can you provide some details on how you get these files?
Thanks in advance!

**Comment by FENGGENYU** [comment]
Thanks for your interest in our paper. 
We use industrial software Deep Exploration 6.3 to extract 3D feature lines.
You can find line illustration in this software and save the line illustration view into the file, eg. eps format, and transfer it into image BMP format.

**Comment by christinazavou** [comment]
Great, thank you! Is there automation (in extracting line illustration and saving the rendered images) with this tool or did you do each model manually?

Another question regarding PSLF... i haven't seen any script in the guidelines that uses pslf code.. could you give some details on when and how you run that?
Thank you:)

**Comment by FENGGENYU** [comment]
Complete_run.m use this file which runs PSLF:
https://github.com/FENGGENYU/proj_style/blob/master/style_analysis/run_kernel_filter.m
