### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by christinazavou** [nicefish666/proj_style#3]
Hello again,

I'm trying to compile the C++ code, and I think the uploaded files are not in their final stage. For example in [sample_and_hog/main.cpp](https://github.com/FENGGENYU/proj_style/blob/da77dedb6cd5014d6c736330658c2c15d038934f/sample_and_hog/main.cpp#L178) BITMAPFILEHEADER doesnt exist, as in readbmp.h it is defined as mytagBITMAPFILEHEADER or myBITMAPFILEHEADER. Also [bfType](https://github.com/FENGGENYU/proj_style/blob/da77dedb6cd5014d6c736330658c2c15d038934f/sample_and_hog/main.cpp#L181) is missing from that struct.

Could you have a look?

Thanks!

**Comment by FENGGENYU** [comment]
Sorry about this bug.

If you want to compile it, please delete function WriteBitmapFile and line 282 on saving BMP files.

The hog feature can be calculated and no need to save extra BMP patch files.
