### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by wy9933** [nicefish666/proj_style#4]
Hi, thanks for your great work!
I am a new one to research 3D shape style, and I downloaded the dataset you provided, but found that it was preprocessed and different from the dataset mentioned in `Co-Locating style-defining Elements on 3D Shapes`, for example, the number of furniture is different and there are no style categories. Could you please tell me how to obtain the dataset of `Co-Locating Style-Defining Elements on 3D Shapes`? I would like to do some experiments based on this dataset. Looking forward to your reply.
Thansk a lot! 😄

**Comment by FENGGENYU** [comment]
Hi, wy.

Our dataset is *not* constructed from data of Co-Locating Style-Defining Elements on 3D Shapes (CLSDE). Our dataset is constructed from models from Internet and other previous works.

We did make comparison to the work of CLSDE, and the authors of that work emailed us their dataset. I don't keep their dataset now.

For our dataset, there is a labels.mat file includes the style label information. And the style label is also indicated by the file name of each obj file, please check it.

Best,

Fenggen

**Comment by wy9933** [comment]
Thanks for your reply!
It's my bad for not double-checking the dataset properly. I'll take another look at it, sorry to bother you.
